### ISSUE TITLE
Dialog for environment variables does not show for automated tests

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-tester-plugin#10]
It seems that for automated tests (at least for geoserver explorer and geogig) the new dialog to setup the endpoints url (and repository folder) do not show.

**Comment by gioman** [comment]
Seems ok now for GeoGig Light plugin, i don't see the dialog show for Geoserver explorer.

**Comment by volaya** [comment]
It should we working now for geoserver plugin as well

**Comment by gioman** [comment]
yes.
