### ISSUE TITLE
Test lists empty after installing/updating the tester plugin

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-tester-plugin#11]
The dialog with the lists is empty immediately after installing or upgrading the tester plugin. Low priority.

**Comment by volaya** [comment]
There is not much we can do about this, I am afraid. The tests will not be added unless the plugin that contains them are reloaded themselves. the tester plugin itself cannot "fetch" the tests. The plugins "plug" them, so the only way would be to implement a more complex mechanism so the plugins liste to plugin updates. Looks a bit overkill to me...

**Comment by gioman** [comment]
no problem.
