### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by dwsilk** [boundlessgeo/qgis-tester-plugin#14]
Could some installation instructions be added to the docs?

As far as I can tell:  
- this isn't part of the official QGIS plugin repository
- it doesn't contain a `metadata.txt` file so adding it to a QGIS plugins dir will not allow it to be recognised as a plugin

**Comment by gioman** [comment]
metadata file is here

https://github.com/boundlessgeo/qgis-tester-plugin/blob/master/qgistester/metadata.txt

the plugin is not part of the official qgis plugin repository because it does not make any sense, the tester plugin is to test Boundless plugins.

**Comment by dwsilk** [comment]
Ah thanks, not sure how I missed that.

[This blog post](https://boundlessgeo.com/2016/07/qgis-continuous-integration-testing-environment-for-python-plugins/) indicates that this plugin could be used to test any QGIS plugin, not just Boundless ones.

**Comment by gioman** [comment]
> This blog post indicates that this plugin could be used to test any QGIS plugin, not just Boundless ones.

sorry I used poor wording. I meant that the Tester allows you to run manual and automated tests for any plugin but to work the tests must be created too.
