### ISSUE TITLE
After clicking "ok" in "test results" dialog return to "test selector"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-tester-plugin#5]
I think that this would be a nice improvement.

**Comment by gioman** [comment]
@volaya the more I use the Tester plugin and the more I think that the dialog with the tests should really be presented again after running test/s (regardless they pass or not).

**Comment by volaya** [comment]
So it should show the report, and when you close the report, again the test selector? I was thinking about showing it, and with the tests from the previous run already selected. What do you think?

**Comment by gioman** [comment]
> So it should show the report, and when you close the report, again the test selector?

yes, this would help a lot in case that a user don't want to run all the test in one go, but rather run them one by one or small batches.




> I was thinking about showing it, and with the tests from the previous run already selected. What do you think?

sounds good to me.

cheers!

**Comment by gioman** [comment]
Seems implemented to me.
